apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
      - name: order-deployment
        image: abhayjo/cc-backend-order:1.0
        ports:
        - containerPort: 8002
        imagePullPolicy: Always

