apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  
