services:

  user-management:
    build: 
        context: ./user-management
        dockerfile: Dockerfile
    image: cc-backend-user:1.0
    ports:
    - "8000:8000"
    volumes:
    - ./user-management:/code

  product-management:
    build: 
        context: ./product-management
        dockerfile: Dockerfile
    image: cc-backend-product:1.0
    ports:
    - "8001:8001"
    volumes:
    - ./product-management:/code

  order-management:
    build: 
        context: ./order-management
        dockerfile: Dockerfile
    image: cc-backend-order:1.0
    ports:
    - "8002:8002"
    volumes:
    - ./order-management:/code
  
  review-management:
    build: 
        context: ./review-management
        dockerfile: Dockerfile
    image: cc-backend-review:1.0
    ports:
    - "8003:8003"
    volumes:
    - ./review-management:/code

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: cc-frontend:1.0
    ports:
    - "8004:8004"
    volumes:
    - ./frontend:/code
    depends_on:
      - user-management
      - product-management
      - order-management
      - review-management
    

networks: 
  my_network:
    driver: bridge
