apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/akshar/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 21 Apr 2024 15:25:04 IST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 21 Apr 2024 15:25:04 IST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/akshar/.minikube/profiles/minikube/client.crt
    client-key: /home/akshar/.minikube/profiles/minikube/client.key
